data_dir: /home/nathanielhoffman/Desktop/cel/physicsnemo/RUN-2
ckpt_path: ./checkpoints
stats_dir: ./stats
cuda_devices: null
train_fraction: 0.8
val_fraction: 0.1
needle_crop_mm: 10.0
tissue_crop_mm: 25.0
slice_half_thickness_mm: 15.0
full_needle_tissue_mm: 7.0
crop_strategy_weights:
- 0.7
- 0.15
- 0.15
input_dim_nodes: 30
input_dim_edges: 7
output_dim: 9
use_fourier_features: false
n_fourier_features: 64
fourier_scale: 0.36
hidden_dim_node_encoder: 256
hidden_dim_edge_encoder: 256
hidden_dim_node_decoder: 256
hidden_dim_processor: 256
processor_size: 15
aggregation: sum
epochs: 300
batch_size: 1
num_workers: 2
lr: 0.0001
amp: false
jit: false
val_every: 10
save_every: 50
infer_start_frame: null
n_rollout: 20
infer_output_dir: ./inference_output
consensus_attenuation: 0.0
wandb_mode: online
wandb_project: PhysicsNeMo-Launch
wandb_entity: nhoffma1
wandb_log_artifact: true
